# Generated by Django 3.2.5 on 2022-02-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_developer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
