# Generated by Django 3.2.5 on 2022-03-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_developer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='username',
        ),
    ]
