# Generated by Django 3.2.5 on 2022-01-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Fresh'), ('2', 'Stucked')], default=1, max_length=7),
        ),
    ]
