# Generated by Django 4.0.1 on 2022-02-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='efforts',
            field=models.IntegerField(),
        ),
    ]
