# Generated by Django 4.0.1 on 2022-02-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_efforts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='person',
            field=models.CharField(default='smitesh', max_length=100),
        ),
    ]
