# Generated by Django 4.0.1 on 2022-02-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='person',
        ),
    ]
