# Generated by Django 4.0.1 on 2022-02-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_project_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='person',
            field=models.CharField(default='smitesh', max_length=100),
        ),
    ]
