# Generated by Django 3.2.5 on 2022-02-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='person',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
