# Generated by Django 4.0.1 on 2022-02-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
