# Generated by Django 4.0.1 on 2022-03-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AddField(
            model_name='reply',
            name='name',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='NULL', max_length=80),
        ),
    ]
